export const SHOW_BUY_MAIL_MODAL = 'SHOW_BUY_MAIL_MODAL';
export const CLOSE_BUY_MAIL_MODAL = 'CLOSE_BUY_MAIL_MODAL';
export const OPEN_LOADING_API = 'OPEN_LOADING_API';
export const CLOSE_LOADING_API = 'CLOSE_LOADING_API';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const CLOSE_CONFIRM_ORDER = 'CLOSE_CONFIRM_ORDER';
export const PAYPAL = 'PAYPAL';
export const CLOSE_PAYPAL = 'CLOSE_PAYPAL';
export const ORDER_ID = 'ORDER_ID';
export const GET_BALANCE = 'GET_BALANCE';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const SHOW_RENT_MAIL_MODAL = 'SHOW_RENT_MAIL_MODAL';
export const ClOSE_RENT_MAIL_MODAL = 'ClOSE_RENT_MAIL_MODAL';
export const STATE_LANGUAGE = 'STATE_LANGUAGE';
export const SHOW_NOTICE_MODAL = 'SHOW_NOTICE_MODAL';
export const CLOSE_NOTICE_MODAL = 'CLOSE_NOTICE_MODAL';









